export const GET_CHARACTERS = "@GET_CHARACTERS";

export const GET_FILTERED = "@GET_FILTERED";
export const ADD_FILTER = "@ADD_FILTER";
export const REMOVE_FILTER = "@REMOVE_FILTER";

export const GET_FAVORITES = "@GET_FAVORITES";
export const ADD_FAVORITE = "@ADD_FAVORITE";
export const REMOVE_FAVORITE = "@REMOVE_FAVORITE";
export const REMOVE_ALL_FAVORITES = "@REMOVE_ALL_FAVORITES";
